name: Push to Firebase

on:
  push:
    branches: [main]

workflow_dispatch:
  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@main
        - name: Install Dependencies
          uses: npm ci
        - name: Build Website
          run: npm run build
        - name: Archive Website Production
          run: actions/upload-artifact@main
          with:
            name: dist
            path: dist
    deploy:
      name: Deploy to Firebase
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@main
        - name: Download Website
          uses: actions/download-artifact@main
          with:
            name: dist
            path: dist
        - name: Deploy Website
          run: w9jds/firebase-deploy@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
